# Generated by Django 4.2.5 on 2023-10-02 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('genre', models.CharField(max_length=6)),
                ('description', models.TextField(verbose_name='Description about the anime.')),
                ('magazine', models.CharField(max_length=20, null=True)),
                ('year', models.FloatField()),
                ('episode', models.IntegerField(null=True, verbose_name='number of episodes')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mangaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Authors', to='api.topanime')),
            ],
        ),
    ]
