# Generated by Django 4.2.5 on 2023-10-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangaka',
            name='mangaka',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mangaka',
            name='review',
            field=models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3three', 'Three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], max_length=6, null=True),
        ),
    ]
